name: Monsters
version: '1.0'
main: de.ethicbuilds.monsters.Main
api-version: '1.21'
authors: [ codedByGruba ]

commands:
  monstersTest:
    description: "Test"
  locateMonsters:
    description: "locate monsters"