name: Monsters
version: '1.0'
main: de.ethicbuilds.monsters.Main
api-version: '1.21'
authors: [ codedByGruba ]

commands:
  createMapConfig:
    description: "create Map config"
  locateMonsters:
    description: "locate monsters"